### ISSUE TITLE
add support for template_oid in the C++ SDK

### ISSUE THREAD

**Issue by mejohnnaylor** [rossvideo/Catena#91]
There are 2 approaches to this:

1) efficient but hard
- unless the inheriting parameter is written to (value, constraint) getValue and getConstraint use the referenced parameter to get these objects.
- once these are written to by setValue or setConstraint a local copy is maintained for future accesses.
- the ParamAccessor class will need to maintain "dirty" flags for all mutable objects in a Param.
2) inefficient but easy
- make a local copy of the referenced parameter

In no circumstances should the inheriting param overwrite the reference param.

**Comment by Isaac-Robert-Ross** [comment]
completed in PR #171, implemented using deep copies into the relevant param
